
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  QirExecutionWrapper\QirExecutionWrapper.bond
//   Output filename: QirExecutionWrapper_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Quantum.QsCompiler.BondSchemas.QirExecutionWrapper
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class EntryPointOperation
    {
        [global::Bond.Id(5)]
        public string Name { get; set; }

        [global::Bond.Id(10)]
        public List<global::Microsoft.Quantum.QsCompiler.BondSchemas.Argument.Argument> Arguments { get; set; }

        public EntryPointOperation()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.QirExecutionWrapper.EntryPointOperation", "EntryPointOperation")
        {}

        protected EntryPointOperation(string fullName, string name)
        {
            Name = "";
            Arguments = new List<global::Microsoft.Quantum.QsCompiler.BondSchemas.Argument.Argument>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class QirExecutionWrapper
    {
        [global::Bond.Id(5)]
        public List<EntryPointOperation> EntryPoints { get; set; }

        [global::Bond.Id(10)]
        public System.ArraySegment<byte> QirBytecode { get; set; }

        public QirExecutionWrapper()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.QirExecutionWrapper.QirExecutionWrapper", "QirExecutionWrapper")
        {}

        protected QirExecutionWrapper(string fullName, string name)
        {
            EntryPoints = new List<EntryPointOperation>();
            QirBytecode = new System.ArraySegment<byte>();
        }
    }
} // Microsoft.Quantum.QsCompiler.BondSchemas.QirExecutionWrapper
