stylecheck:
	@source develop.env && python -m PassCI --stylecheck



lint:
	@echo "Static analysis not added yet"

tests:
	@source develop.env && python -m PassCI test

clean:
	rm -rf Release/
	rm -rf Debug/
