/src/QsCompiler/CommandLineTool @samarsha @cesarzc
/src/QsCompiler/CompilationManager @samarsha @cesarzc
/src/QsCompiler/Compiler @samarsha @cesarzc
/src/QsCompiler/Core @samarsha @cesarzc
/src/QsCompiler/DataStructures @samarsha @cesarzc
/src/QsCompiler/SyntaxProcessor @samarsha @cesarzc
/src/QsCompiler/Tests.Compiler @samarsha @cesarzc
/src/QsCompiler/TextProcessor @samarsha @cesarzc

/src/QsCompiler/Optimizations @samarsha

/src/QsCompiler/BondSchemas @cesarzc
/src/QsCompiler/TestTargets @swernli @cesarzc

/src/QsCompiler/LanguageServer @samarsha @swernli
/src/QsCompiler/TestProjects @samarsha @swernli
/src/QsCompiler/Tests.LanguageServer @samarsha @swernli

/examples/QIR @swernli @bettinaheim
/src/QsCompiler/CSharpGeneration @swernli @bettinaheim
/src/QsCompiler/LlvmBindings @swernli @bettinaheim
/src/QsCompiler/QirGeneration @swernli @bettinaheim
/src/QsCompiler/RoslynWrapper @swernli @bettinaheim
/src/QsCompiler/Tests.CSharpGeneration @swernli @bettinaheim
/src/QsCompiler/Tests.RoslynWrapper @swernli @bettinaheim
/src/QuantumSdk @swernli @bettinaheim

/src/QsCompiler/Transformations @samarsha @ScottCarda-MS
/src/QsFmt @ScottCarda-MS @samarsha
