
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  Execution\Execution.bond
//   Output filename: Execution_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Quantum.QsCompiler.BondSchemas.Execution
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum DataType
    {
        BoolType,
        IntegerType,
        DoubleType,
        PauliType,
        RangeType,
        ResultType,
        StringType,
        ArrayType,
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum PauliValue
    {
        PauliI,
        PauliX,
        PauliY,
        PauliZ,
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RangeValue
    {
        [global::Bond.Id(5)]
        public long Start { get; set; }

        [global::Bond.Id(10)]
        public long Step { get; set; }

        [global::Bond.Id(15)]
        public long End { get; set; }

        public RangeValue()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.Execution.RangeValue", "RangeValue")
        {}

        protected RangeValue(string fullName, string name)
        {
            
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum ResultValue
    {
        Zero,
        One,
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Argument
    {
        [global::Bond.Id(5)]
        public string Name { get; set; }

        [global::Bond.Id(10)]
        public DataType Type { get; set; }

        [global::Bond.Id(15)]
        public int Position { get; set; }

        public Argument()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.Execution.Argument", "Argument")
        {}

        protected Argument(string fullName, string name)
        {
            Name = "";
            Type = DataType.BoolType;
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ArgumentValue
    {
        [global::Bond.Id(5)]
        public DataType Type { get; set; }

        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<bool>))]
        public bool? Bool { get; set; }

        [global::Bond.Id(15), global::Bond.Type(typeof(global::Bond.Tag.nullable<long>))]
        public long? Integer { get; set; }

        [global::Bond.Id(20), global::Bond.Type(typeof(global::Bond.Tag.nullable<double>))]
        public double? Double { get; set; }

        [global::Bond.Id(25), global::Bond.Type(typeof(global::Bond.Tag.nullable<PauliValue>))]
        public PauliValue? Pauli { get; set; }

        [global::Bond.Id(30), global::Bond.Type(typeof(global::Bond.Tag.nullable<RangeValue>))]
        public RangeValue Range { get; set; }

        [global::Bond.Id(35), global::Bond.Type(typeof(global::Bond.Tag.nullable<ResultValue>))]
        public ResultValue? Result { get; set; }

        [global::Bond.Id(40), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string String { get; set; }

        [global::Bond.Id(45), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<ArgumentValue>>))]
        public List<ArgumentValue> Array { get; set; }

        public ArgumentValue()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.Execution.ArgumentValue", "ArgumentValue")
        {}

        protected ArgumentValue(string fullName, string name)
        {
            Type = DataType.BoolType;
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class EntryPointOperation
    {
        [global::Bond.Id(5)]
        public string Name { get; set; }

        [global::Bond.Id(10)]
        public List<Argument> Arguments { get; set; }

        public EntryPointOperation()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.Execution.EntryPointOperation", "EntryPointOperation")
        {}

        protected EntryPointOperation(string fullName, string name)
        {
            Name = "";
            Arguments = new List<Argument>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ExecutionInformation
    {
        [global::Bond.Id(5)]
        public EntryPointOperation EntryPoint { get; set; }

        [global::Bond.Id(10)]
        public Dictionary<string, ArgumentValue> ArgumentValues { get; set; }

        public ExecutionInformation()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.Execution.ExecutionInformation", "ExecutionInformation")
        {}

        protected ExecutionInformation(string fullName, string name)
        {
            EntryPoint = new EntryPointOperation();
            ArgumentValues = new Dictionary<string, ArgumentValue>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class QirExecutionWrapper
    {
        [global::Bond.Id(5)]
        public List<ExecutionInformation> Executions { get; set; }

        [global::Bond.Id(10)]
        public System.ArraySegment<byte> QirBytecode { get; set; }

        public QirExecutionWrapper()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.Execution.QirExecutionWrapper", "QirExecutionWrapper")
        {}

        protected QirExecutionWrapper(string fullName, string name)
        {
            Executions = new List<ExecutionInformation>();
            QirBytecode = new System.ArraySegment<byte>();
        }
    }
} // Microsoft.Quantum.QsCompiler.BondSchemas.Execution
