
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  C:\Microsoft\ReposB\qsharp-compiler\src\QsCompiler\BondSchemas\V2\CompilerDataStructuresV2.bond
//   Output filename: CompilerDataStructuresV2_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Quantum.QsCompiler.BondSchemas.V2
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class QsNamespace
    {
        [global::Bond.Id(5)]
        public string Name { get; set; }

        [global::Bond.Id(10)]
        public List<global::Microsoft.Quantum.QsCompiler.BondSchemas.V1.QsNamespaceElement> Elements { get; set; }

        [global::Bond.Id(15)]
        public LinkedList<global::Bond.IBonded<global::Microsoft.Quantum.QsCompiler.BondSchemas.V1.QsSourceFileDocumentation>> Documentation { get; set; }

        public QsNamespace()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.V2.QsNamespace", "QsNamespace")
        {}

        protected QsNamespace(string fullName, string name)
        {
            Name = "";
            Elements = new List<global::Microsoft.Quantum.QsCompiler.BondSchemas.V1.QsNamespaceElement>();
            Documentation = new LinkedList<global::Bond.IBonded<global::Microsoft.Quantum.QsCompiler.BondSchemas.V1.QsSourceFileDocumentation>>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class QsCompilation
    {
        [global::Bond.Id(5)]
        public List<QsNamespace> Namespaces { get; set; }

        [global::Bond.Id(10)]
        public List<global::Microsoft.Quantum.QsCompiler.BondSchemas.V1.QsQualifiedName> EntryPoints { get; set; }

        public QsCompilation()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.V2.QsCompilation", "QsCompilation")
        {}

        protected QsCompilation(string fullName, string name)
        {
            Namespaces = new List<QsNamespace>();
            EntryPoints = new List<global::Microsoft.Quantum.QsCompiler.BondSchemas.V1.QsQualifiedName>();
        }
    }
} // Microsoft.Quantum.QsCompiler.BondSchemas.V2
