
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  EntryPoint\EntryPoint.bond
//   Output filename: EntryPoint_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Quantum.QsCompiler.BondSchemas.EntryPoint
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum DataType
    {
        BoolType,
        IntegerType,
        DoubleType,
        PauliType,
        RangeType,
        ResultType,
        StringType,
        ArrayType,
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum PauliValue
    {
        PauliI,
        PauliX,
        PauliY,
        PauliZ,
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RangeValue
    {
        [global::Bond.Id(5)]
        public long Start { get; set; }

        [global::Bond.Id(10)]
        public long Step { get; set; }

        [global::Bond.Id(15)]
        public long End { get; set; }

        public RangeValue()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.EntryPoint.RangeValue", "RangeValue")
        {}

        protected RangeValue(string fullName, string name)
        {
            
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum ResultValue
    {
        Zero,
        One,
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ArrayValue
    {
        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<bool>>))]
        public List<bool> Bool { get; set; }

        [global::Bond.Id(15), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<long>>))]
        public List<long> Integer { get; set; }

        [global::Bond.Id(20), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<double>>))]
        public List<double> Double { get; set; }

        [global::Bond.Id(25), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<PauliValue>>))]
        public List<PauliValue> Pauli { get; set; }

        [global::Bond.Id(30), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<RangeValue>>))]
        public List<RangeValue> Range { get; set; }

        [global::Bond.Id(35), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<ResultValue>>))]
        public List<ResultValue> Result { get; set; }

        public ArrayValue()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.EntryPoint.ArrayValue", "ArrayValue")
        {}

        protected ArrayValue(string fullName, string name)
        {
            
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ArgumentValue
    {
        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<bool>))]
        public bool? Bool { get; set; }

        [global::Bond.Id(15), global::Bond.Type(typeof(global::Bond.Tag.nullable<long>))]
        public long? Integer { get; set; }

        [global::Bond.Id(20), global::Bond.Type(typeof(global::Bond.Tag.nullable<double>))]
        public double? Double { get; set; }

        [global::Bond.Id(25), global::Bond.Type(typeof(global::Bond.Tag.nullable<PauliValue>))]
        public PauliValue? Pauli { get; set; }

        [global::Bond.Id(30), global::Bond.Type(typeof(global::Bond.Tag.nullable<RangeValue>))]
        public RangeValue Range { get; set; }

        [global::Bond.Id(35), global::Bond.Type(typeof(global::Bond.Tag.nullable<ResultValue>))]
        public ResultValue? Result { get; set; }

        [global::Bond.Id(40), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string String { get; set; }

        [global::Bond.Id(45), global::Bond.Type(typeof(global::Bond.Tag.nullable<ArrayValue>))]
        public ArrayValue Array { get; set; }

        public ArgumentValue()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.EntryPoint.ArgumentValue", "ArgumentValue")
        {}

        protected ArgumentValue(string fullName, string name)
        {
            
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Argument
    {
        [global::Bond.Id(5)]
        public DataType Type { get; set; }

        [global::Bond.Id(10)]
        public string Name { get; set; }

        [global::Bond.Id(15)]
        public int Position { get; set; }

        [global::Bond.Id(20), global::Bond.Type(typeof(global::Bond.Tag.nullable<DataType>))]
        public DataType? ArrayType { get; set; }

        [global::Bond.Id(25)]
        public List<ArgumentValue> Values { get; set; }

        public Argument()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.EntryPoint.Argument", "Argument")
        {}

        protected Argument(string fullName, string name)
        {
            Type = DataType.BoolType;
            Name = "";
            Values = new List<ArgumentValue>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class EntryPointOperation
    {
        [global::Bond.Id(5)]
        public string Name { get; set; }

        [global::Bond.Id(10)]
        public List<Argument> Arguments { get; set; }

        public EntryPointOperation()
            : this("Microsoft.Quantum.QsCompiler.BondSchemas.EntryPoint.EntryPointOperation", "EntryPointOperation")
        {}

        protected EntryPointOperation(string fullName, string name)
        {
            Name = "";
            Arguments = new List<Argument>();
        }
    }
} // Microsoft.Quantum.QsCompiler.BondSchemas.EntryPoint
