//------------------------------------------------------------------------------
// This code was generated by a tool.
// <auto-generated />
//------------------------------------------------------------------------------

extern "C" void UseBoolArg(); // NOLINT

int main(int argc, char* argv[])
{
    return 0;
}
