all:
	cd SimpleLoop && make all && make clean
	cd TeleportChain && make all && make clean
	cd LoopRecursion && make all && make clean
	cd ConstArray && make all && make clean


clean:
	cd SimpleLoop && make clean	
	cd TeleportChain && make clean	
	cd LoopRecursion && make clean
	cd ConstArray &&  make clean
