all:
	cd SimpleLoop && make all && make clean
	cd TeleportChain && make all && make clean
	cd LoopRecursion && make all && make clean
	cd RandomWalkPE1 && make all && make clean
	cd RandomWalkPE2 && make all && make clean
	cd ConstArray && make all && make clean
	cd Grover && make all && make clean
	cd HiddenShift && make all && make clean	
	cd IsingModel && make all && make clean
	cd ParallelQRng && make all && make clean


clean:
	cd SimpleLoop && make clean	
	cd TeleportChain && make clean	
	cd LoopRecursion && make clean
	cd RandomWalkPE1 && make clean
	cd RandomWalkPE2 && make clean
	cd ConstArray &&  make clean
	cd Grover && make clean
	cd HiddenShift && make clean	
	cd IsingModel && make clean
	cd ParallelQRng && make clean
