#pragma once
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "Llvm/Llvm.hpp"

#include <unordered_map>
#include <vector>

namespace microsoft
{
namespace quantum
{

    /// QirAllocationAnalysis is a LLVM pass that statistics on the usage of operations which allocates
    /// resources such as qubits and results.
    class QirAllocationAnalysis : public llvm::AnalysisInfoMixin<QirAllocationAnalysis>
    {
      public:
        using String = std::string;

        /// Result annotation. Contains a single value which
        /// is true if the function uses allocations of qubits or results.
        struct Result
        {
            bool value{false};
        };

        /// Constructors and destructors
        /// @{
        QirAllocationAnalysis()                             = default;
        QirAllocationAnalysis(QirAllocationAnalysis const&) = delete;
        QirAllocationAnalysis(QirAllocationAnalysis&&)      = default;
        ~QirAllocationAnalysis()                            = default;
        /// @}

        /// Operators
        /// @{
        QirAllocationAnalysis& operator=(QirAllocationAnalysis const&) = delete;
        QirAllocationAnalysis& operator=(QirAllocationAnalysis&&) = delete;
        /// @}

        /// Functions required by LLVM
        /// @{
        Result run(llvm::Function& function, llvm::FunctionAnalysisManager& /*unused*/);
        /// @}

      private:
        static llvm::AnalysisKey Key; // NOLINT
        friend struct llvm::AnalysisInfoMixin<QirAllocationAnalysis>;
    };

    /// QirAllocationAnalysisPrinter is a LLVM pass class that prints statistics generated by
    /// QirAllocationAnalysis.
    class QirAllocationAnalysisPrinter : public llvm::PassInfoMixin<QirAllocationAnalysisPrinter>
    {
      public:
        /// Constructors and destructors
        /// @{
        explicit QirAllocationAnalysisPrinter(llvm::raw_ostream& out_stream);
        QirAllocationAnalysisPrinter()                                    = delete;
        QirAllocationAnalysisPrinter(QirAllocationAnalysisPrinter const&) = delete;
        QirAllocationAnalysisPrinter(QirAllocationAnalysisPrinter&&)      = default;
        ~QirAllocationAnalysisPrinter()                                   = default;
        /// @}

        /// Operators
        /// @{
        QirAllocationAnalysisPrinter& operator=(QirAllocationAnalysisPrinter const&) = delete;
        QirAllocationAnalysisPrinter& operator=(QirAllocationAnalysisPrinter&&) = delete;
        /// @}

        /// Functions required by LLVM
        /// @{
        llvm::PreservedAnalyses run(llvm::Function& function, llvm::FunctionAnalysisManager& fam);
        static bool             isRequired();
        /// @}
      private:
        llvm::raw_ostream& out_stream_;
    };

} // namespace quantum
} // namespace microsoft
