all:
	cd TeleportChain && make all && make clean
	cd LoopRecursion && make all && make clean
	cd RandomWalkPE1 && make all && make clean
	cd RandomWalkPE2 && make all && make clean

clean:
	cd TeleportChain && make clean
	cd LoopRecursion && make clean
	cd RandomWalkPE1 && make clean
	cd RandomWalkPE2 && make clean
