/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    Version: 2019.03 Build: release Linux 64-bit                         */
/*    C Header output                                                      */
/*                                                                         */
/* Command Line:                                                           */
/*    /home/cad/tools/semifore/csrcompiler/2019_03/bin/x64_re6/csrCompile  */
/*    -v -x CSRSpec -t h -t sv -t docx -a fkb_dig_rcl_csr -o               */
/*    fkb_dig_rcl_csr rcl_csr.csr                                          */
/*                                                                         */
/* Input files:                                                            */
/*    rcl_csr.csr                                                          */
/*                                                                         */
/* Generated on: Wed Oct 23 10:56:10 2019                                  */
/*           by: dusouder                                                  */
/*                                                                         */

#ifndef _FKB_DIG_RCL_CSR_H_
#define _FKB_DIG_RCL_CSR_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: fkb_dig_rcl_csr                           */
/* Source filename: rcl_csr.csr, line: 2351                                */
/* Memory: fkb_dig_rcl_csr.rclMemory                                       */
#define FKB_DIG_RCL_CSR_RCLMEMORY_ADDRESS 0x0ul
#define FKB_DIG_RCL_CSR_RCLMEMORY_BYTE_ADDRESS 0x0ul
/* Register: fkb_dig_rcl_csr.rRscratch                                     */
#define FKB_DIG_RCL_CSR_RRSCRATCH_ADDRESS 0x1000000ul
#define FKB_DIG_RCL_CSR_RRSCRATCH_BYTE_ADDRESS 0x1000000ul
/* Register: fkb_dig_rcl_csr.rRctl                                         */
#define FKB_DIG_RCL_CSR_RRCTL_ADDRESS 0x1000004ul
#define FKB_DIG_RCL_CSR_RRCTL_BYTE_ADDRESS 0x1000004ul
/* Register: fkb_dig_rcl_csr.rRcfg0                                        */
#define FKB_DIG_RCL_CSR_RRCFG0_ADDRESS 0x1000008ul
#define FKB_DIG_RCL_CSR_RRCFG0_BYTE_ADDRESS 0x1000008ul
/* Register: fkb_dig_rcl_csr.rRcfg1                                        */
#define FKB_DIG_RCL_CSR_RRCFG1_ADDRESS 0x100000cul
#define FKB_DIG_RCL_CSR_RRCFG1_BYTE_ADDRESS 0x100000cul
/* Register: fkb_dig_rcl_csr.rRgs0                                         */
#define FKB_DIG_RCL_CSR_RRGS0_ADDRESS 0x1000010ul
#define FKB_DIG_RCL_CSR_RRGS0_BYTE_ADDRESS 0x1000010ul
/* Register: fkb_dig_rcl_csr.rRgs1                                         */
#define FKB_DIG_RCL_CSR_RRGS1_ADDRESS 0x1000014ul
#define FKB_DIG_RCL_CSR_RRGS1_BYTE_ADDRESS 0x1000014ul
/* Register: fkb_dig_rcl_csr.rRgs2                                         */
#define FKB_DIG_RCL_CSR_RRGS2_ADDRESS 0x1000018ul
#define FKB_DIG_RCL_CSR_RRGS2_BYTE_ADDRESS 0x1000018ul
/* Register: fkb_dig_rcl_csr.rRfsgctl                                      */
#define FKB_DIG_RCL_CSR_RRFSGCTL_ADDRESS 0x100001cul
#define FKB_DIG_RCL_CSR_RRFSGCTL_BYTE_ADDRESS 0x100001cul
/* Register: fkb_dig_rcl_csr.rRfsgcfg                                      */
#define FKB_DIG_RCL_CSR_RRFSGCFG_ADDRESS 0x1000020ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_BYTE_ADDRESS 0x1000020ul
/* Register: fkb_dig_rcl_csr.rRend                                         */
#define FKB_DIG_RCL_CSR_RREND_ADDRESS 0x100fffcul
#define FKB_DIG_RCL_CSR_RREND_BYTE_ADDRESS 0x100fffcul


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: fkb_dig_rcl_csr                                        */
/* Addressmap template: fkb_dig_rcl_csr                                    */
/* Source filename: rcl_csr.csr, line: 1630                                */
#define FKB_DIG_RCL_CSR_SIZE 0x2000000ul
#define FKB_DIG_RCL_CSR_BYTE_SIZE 0x2000000ul
/* Memory member: fkb_dig_rcl_csr.rclMemory                                */
/* Memory type referenced: fkb_dig_rcl_csr::rclMemory                      */
/* Memory template referenced: fkb_dig_rcl_csr::rclMemory                  */
#define FKB_DIG_RCL_CSR_RCLMEMORY_OFFSET 0x0ul
#define FKB_DIG_RCL_CSR_RCLMEMORY_BYTE_OFFSET 0x0ul
#define FKB_DIG_RCL_CSR_RCLMEMORY_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RCLMEMORY_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RCLMEMORY_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RCLMEMORY_WRITE_MASK 0xfffffffful
/* Register member: fkb_dig_rcl_csr.rRscratch                              */
/* Register type referenced: fkb_dig_rcl_csr::rRscratch                    */
/* Register template referenced: fkb_dig_rcl_csr::rRscratch                */
#define FKB_DIG_RCL_CSR_RRSCRATCH_OFFSET 0x1000000ul
#define FKB_DIG_RCL_CSR_RRSCRATCH_BYTE_OFFSET 0x1000000ul
#define FKB_DIG_RCL_CSR_RRSCRATCH_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRSCRATCH_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRSCRATCH_RESET_VALUE 0x00000000ul
#define FKB_DIG_RCL_CSR_RRSCRATCH_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRSCRATCH_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRSCRATCH_WRITE_MASK 0xfffffffful
/* Register member: fkb_dig_rcl_csr.rRctl                                  */
/* Register type referenced: fkb_dig_rcl_csr::rRctl                        */
/* Register template referenced: fkb_dig_rcl_csr::rRctl                    */
#define FKB_DIG_RCL_CSR_RRCTL_OFFSET 0x1000004ul
#define FKB_DIG_RCL_CSR_RRCTL_BYTE_OFFSET 0x1000004ul
#define FKB_DIG_RCL_CSR_RRCTL_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCTL_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCTL_RESET_VALUE 0x00000000ul
#define FKB_DIG_RCL_CSR_RRCTL_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRCTL_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRCTL_WRITE_MASK 0x00000001ul
/* Register member: fkb_dig_rcl_csr.rRcfg0                                 */
/* Register type referenced: fkb_dig_rcl_csr::rRcfg0                       */
/* Register template referenced: fkb_dig_rcl_csr::rRcfg0                   */
#define FKB_DIG_RCL_CSR_RRCFG0_OFFSET 0x1000008ul
#define FKB_DIG_RCL_CSR_RRCFG0_BYTE_OFFSET 0x1000008ul
#define FKB_DIG_RCL_CSR_RRCFG0_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG0_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG0_RESET_VALUE 0x1fff0000ul
#define FKB_DIG_RCL_CSR_RRCFG0_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRCFG0_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRCFG0_WRITE_MASK 0x1fff0001ul
/* Register member: fkb_dig_rcl_csr.rRcfg1                                 */
/* Register type referenced: fkb_dig_rcl_csr::rRcfg1                       */
/* Register template referenced: fkb_dig_rcl_csr::rRcfg1                   */
#define FKB_DIG_RCL_CSR_RRCFG1_OFFSET 0x100000cul
#define FKB_DIG_RCL_CSR_RRCFG1_BYTE_OFFSET 0x100000cul
#define FKB_DIG_RCL_CSR_RRCFG1_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG1_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG1_RESET_VALUE 0x00000000ul
#define FKB_DIG_RCL_CSR_RRCFG1_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRCFG1_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRCFG1_WRITE_MASK 0x00fffffful
/* Register member: fkb_dig_rcl_csr.rRgs0                                  */
/* Register type referenced: fkb_dig_rcl_csr::rRgs0                        */
/* Register template referenced: fkb_dig_rcl_csr::rRgs0                    */
#define FKB_DIG_RCL_CSR_RRGS0_OFFSET 0x1000010ul
#define FKB_DIG_RCL_CSR_RRGS0_BYTE_OFFSET 0x1000010ul
#define FKB_DIG_RCL_CSR_RRGS0_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS0_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS0_RESET_VALUE 0x00000010ul
#define FKB_DIG_RCL_CSR_RRGS0_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRGS0_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRGS0_WRITE_MASK 0x00000000ul
/* Register member: fkb_dig_rcl_csr.rRgs1                                  */
/* Register type referenced: fkb_dig_rcl_csr::rRgs1                        */
/* Register template referenced: fkb_dig_rcl_csr::rRgs1                    */
#define FKB_DIG_RCL_CSR_RRGS1_OFFSET 0x1000014ul
#define FKB_DIG_RCL_CSR_RRGS1_BYTE_OFFSET 0x1000014ul
#define FKB_DIG_RCL_CSR_RRGS1_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS1_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS1_RESET_VALUE 0x00000000ul
#define FKB_DIG_RCL_CSR_RRGS1_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRGS1_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRGS1_WRITE_MASK 0x00000000ul
/* Register member: fkb_dig_rcl_csr.rRgs2                                  */
/* Register type referenced: fkb_dig_rcl_csr::rRgs2                        */
/* Register template referenced: fkb_dig_rcl_csr::rRgs2                    */
#define FKB_DIG_RCL_CSR_RRGS2_OFFSET 0x1000018ul
#define FKB_DIG_RCL_CSR_RRGS2_BYTE_OFFSET 0x1000018ul
#define FKB_DIG_RCL_CSR_RRGS2_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS2_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS2_RESET_VALUE 0x00000001ul
#define FKB_DIG_RCL_CSR_RRGS2_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRGS2_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRGS2_WRITE_MASK 0x00000000ul
/* Register member: fkb_dig_rcl_csr.rRfsgctl                               */
/* Register type referenced: fkb_dig_rcl_csr::rRfsgctl                     */
/* Register template referenced: fkb_dig_rcl_csr::rRfsgctl                 */
#define FKB_DIG_RCL_CSR_RRFSGCTL_OFFSET 0x100001cul
#define FKB_DIG_RCL_CSR_RRFSGCTL_BYTE_OFFSET 0x100001cul
#define FKB_DIG_RCL_CSR_RRFSGCTL_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_RESET_VALUE 0x00000002ul
#define FKB_DIG_RCL_CSR_RRFSGCTL_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRFSGCTL_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRFSGCTL_WRITE_MASK 0x000003fful
/* Register member: fkb_dig_rcl_csr.rRfsgcfg                               */
/* Register type referenced: fkb_dig_rcl_csr::rRfsgcfg                     */
/* Register template referenced: fkb_dig_rcl_csr::rRfsgcfg                 */
#define FKB_DIG_RCL_CSR_RRFSGCFG_OFFSET 0x1000020ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_BYTE_OFFSET 0x1000020ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_RESET_VALUE 0x00000000ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRFSGCFG_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRFSGCFG_WRITE_MASK 0xffff7ffful
/* Register member: fkb_dig_rcl_csr.rRend                                  */
/* Register type referenced: fkb_dig_rcl_csr::rRend                        */
/* Register template referenced: fkb_dig_rcl_csr::rRend                    */
#define FKB_DIG_RCL_CSR_RREND_OFFSET 0x100fffcul
#define FKB_DIG_RCL_CSR_RREND_BYTE_OFFSET 0x100fffcul
#define FKB_DIG_RCL_CSR_RREND_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RREND_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RREND_RESET_VALUE 0x00000000ul
#define FKB_DIG_RCL_CSR_RREND_RESET_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RREND_READ_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RREND_WRITE_MASK 0x00000000ul

/* Memory type: fkb_dig_rcl_csr::rclMemory                                 */
/* Memory template: fkb_dig_rcl_csr::rclMemory                             */
/* Source filename: rcl_csr.csr, line: 1651                                */
#define FKB_DIG_RCL_CSR_RCLMEMORY_SIZE 0x2000u
#define FKB_DIG_RCL_CSR_RCLMEMORY_BYTE_SIZE 0x2000u
#define FKB_DIG_RCL_CSR_RCLMEMORY_ENTRIES 0x800ull
#define FKB_DIG_RCL_CSR_RCLMEMORY_MSB 31u
#define FKB_DIG_RCL_CSR_RCLMEMORY_LSB 0u
#define FKB_DIG_RCL_CSR_RCLMEMORY_WIDTH 32u
#define FKB_DIG_RCL_CSR_RCLMEMORY_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RCLMEMORY_GET(x) ((x) & 0xfffffffful)
#define FKB_DIG_RCL_CSR_RCLMEMORY_SET(x) ((x) & 0xfffffffful)

/* Register type: fkb_dig_rcl_csr::rRscratch                               */
/* Register template: fkb_dig_rcl_csr::rRscratch                           */
/* Source filename: rcl_csr.csr, line: 1663                                */
/* Field member: fkb_dig_rcl_csr::rRscratch.val                            */
/* Source filename: rcl_csr.csr, line: 1675                                */
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_MSB 31u
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_LSB 0u
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_WIDTH 32u
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_RESET 0x00000000ul
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_FIELD_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_GET(x) ((x) & 0xfffffffful)
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_SET(x) ((x) & 0xfffffffful)
#define FKB_DIG_RCL_CSR_RRSCRATCH_VAL_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: fkb_dig_rcl_csr::rRctl                                   */
/* Register template: fkb_dig_rcl_csr::rRctl                               */
/* Source filename: rcl_csr.csr, line: 1691                                */
/* Field member: fkb_dig_rcl_csr::rRctl.fsmActive                          */
/* Source filename: rcl_csr.csr, line: 1703                                */
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_MSB 0u
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_LSB 0u
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_FIELD_MASK 0x00000001ul
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_GET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_SET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRCTL_FSMACTIVE_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: fkb_dig_rcl_csr::rRcfg0                                  */
/* Register template: fkb_dig_rcl_csr::rRcfg0                              */
/* Source filename: rcl_csr.csr, line: 1729                                */
/* Field member: fkb_dig_rcl_csr::rRcfg0.sampleCntPlusOneInit              */
/* Source filename: rcl_csr.csr, line: 1773                                */
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_MSB 28u
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_LSB 16u
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_WIDTH 13u
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_RESET 0x1fffu
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_FIELD_MASK 0x1fff0000ul
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_GET(x) \
   (((x) & 0x1fff0000ul) >> 16)
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_SET(x) \
   (((x) << 16) & 0x1fff0000ul)
#define FKB_DIG_RCL_CSR_RRCFG0_SAMPLECNTPLUSONEINIT_MODIFY(r, x) \
   ((((x) << 16) & 0x1fff0000ul) | ((r) & 0xe000fffful))
/* Field member: fkb_dig_rcl_csr::rRcfg0.mode                              */
/* Source filename: rcl_csr.csr, line: 1741                                */
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_MSB 0u
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_LSB 0u
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_FIELD_MASK 0x00000001ul
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_GET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_SET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRCFG0_MODE_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: fkb_dig_rcl_csr::rRcfg1                                  */
/* Register template: fkb_dig_rcl_csr::rRcfg1                              */
/* Source filename: rcl_csr.csr, line: 1797                                */
/* Field member: fkb_dig_rcl_csr::rRcfg1.replayCntInit                     */
/* Source filename: rcl_csr.csr, line: 1809                                */
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_MSB 23u
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_LSB 0u
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_WIDTH 24u
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_RESET 0x000000ul
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_FIELD_MASK 0x00fffffful
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_GET(x) ((x) & 0x00fffffful)
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_SET(x) ((x) & 0x00fffffful)
#define FKB_DIG_RCL_CSR_RRCFG1_REPLAYCNTINIT_MODIFY(r, x) \
   (((x) & 0x00fffffful) | ((r) & 0xff000000ul))

/* Register type: fkb_dig_rcl_csr::rRgs0                                   */
/* Register template: fkb_dig_rcl_csr::rRgs0                               */
/* Source filename: rcl_csr.csr, line: 1837                                */
/* Field member: fkb_dig_rcl_csr::rRgs0.loopCnt                            */
/* Source filename: rcl_csr.csr, line: 1879                                */
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_MSB 31u
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_LSB 16u
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_WIDTH 16u
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_RESET 0x0000u
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_FIELD_MASK 0xffff0000ul
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_GET(x) (((x) & 0xffff0000ul) >> 16)
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_SET(x) (((x) << 16) & 0xffff0000ul)
#define FKB_DIG_RCL_CSR_RRGS0_LOOPCNT_MODIFY(r, x) \
   ((((x) << 16) & 0xffff0000ul) | ((r) & 0x0000fffful))
/* Field member: fkb_dig_rcl_csr::rRgs0.fsm                                */
/* Source filename: rcl_csr.csr, line: 1849                                */
#define FKB_DIG_RCL_CSR_RRGS0_FSM_MSB 4u
#define FKB_DIG_RCL_CSR_RRGS0_FSM_LSB 0u
#define FKB_DIG_RCL_CSR_RRGS0_FSM_WIDTH 5u
#define FKB_DIG_RCL_CSR_RRGS0_FSM_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS0_FSM_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS0_FSM_RESET 0x10u
#define FKB_DIG_RCL_CSR_RRGS0_FSM_FIELD_MASK 0x0000001ful
#define FKB_DIG_RCL_CSR_RRGS0_FSM_GET(x) ((x) & 0x0000001ful)
#define FKB_DIG_RCL_CSR_RRGS0_FSM_SET(x) ((x) & 0x0000001ful)
#define FKB_DIG_RCL_CSR_RRGS0_FSM_MODIFY(r, x) \
   (((x) & 0x0000001ful) | ((r) & 0xffffffe0ul))

/* Register type: fkb_dig_rcl_csr::rRgs1                                   */
/* Register template: fkb_dig_rcl_csr::rRgs1                               */
/* Source filename: rcl_csr.csr, line: 1917                                */
/* Field member: fkb_dig_rcl_csr::rRgs1.sampleCnt                          */
/* Source filename: rcl_csr.csr, line: 1929                                */
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_MSB 23u
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_LSB 0u
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_WIDTH 24u
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_RESET 0x000000ul
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_FIELD_MASK 0x00fffffful
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_GET(x) ((x) & 0x00fffffful)
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_SET(x) ((x) & 0x00fffffful)
#define FKB_DIG_RCL_CSR_RRGS1_SAMPLECNT_MODIFY(r, x) \
   (((x) & 0x00fffffful) | ((r) & 0xff000000ul))

/* Register type: fkb_dig_rcl_csr::rRgs2                                   */
/* Register template: fkb_dig_rcl_csr::rRgs2                               */
/* Source filename: rcl_csr.csr, line: 1975                                */
/* Field member: fkb_dig_rcl_csr::rRgs2.word_cnt                           */
/* Source filename: rcl_csr.csr, line: 2027                                */
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_MSB 5u
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_LSB 2u
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_WIDTH 4u
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_FIELD_MASK 0x0000003cul
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_GET(x) (((x) & 0x0000003cul) >> 2)
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_SET(x) (((x) << 2) & 0x0000003cul)
#define FKB_DIG_RCL_CSR_RRGS2_WORD_CNT_MODIFY(r, x) \
   ((((x) << 2) & 0x0000003cul) | ((r) & 0xffffffc3ul))
/* Field member: fkb_dig_rcl_csr::rRgs2.full                               */
/* Source filename: rcl_csr.csr, line: 2007                                */
#define FKB_DIG_RCL_CSR_RRGS2_FULL_MSB 1u
#define FKB_DIG_RCL_CSR_RRGS2_FULL_LSB 1u
#define FKB_DIG_RCL_CSR_RRGS2_FULL_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRGS2_FULL_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS2_FULL_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS2_FULL_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRGS2_FULL_FIELD_MASK 0x00000002ul
#define FKB_DIG_RCL_CSR_RRGS2_FULL_GET(x) (((x) & 0x00000002ul) >> 1)
#define FKB_DIG_RCL_CSR_RRGS2_FULL_SET(x) (((x) << 1) & 0x00000002ul)
#define FKB_DIG_RCL_CSR_RRGS2_FULL_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: fkb_dig_rcl_csr::rRgs2.empty                              */
/* Source filename: rcl_csr.csr, line: 1987                                */
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_MSB 0u
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_LSB 0u
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_RESET 0x1u
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_FIELD_MASK 0x00000001ul
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_GET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_SET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRGS2_EMPTY_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: fkb_dig_rcl_csr::rRfsgctl                                */
/* Register template: fkb_dig_rcl_csr::rRfsgctl                            */
/* Source filename: rcl_csr.csr, line: 2049                                */
/* Field member: fkb_dig_rcl_csr::rRfsgctl.dac_bypass                      */
/* Source filename: rcl_csr.csr, line: 2091                                */
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_MSB 9u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_LSB 2u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_WIDTH 8u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_RESET 0x00u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_FIELD_MASK 0x000003fcul
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_GET(x) \
   (((x) & 0x000003fcul) >> 2)
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SET(x) \
   (((x) << 2) & 0x000003fcul)
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_MODIFY(r, x) \
   ((((x) << 2) & 0x000003fcul) | ((r) & 0xfffffc03ul))
/* Field member: fkb_dig_rcl_csr::rRfsgctl.dac_bypass_sel                  */
/* Source filename: rcl_csr.csr, line: 2079                                */
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_MSB 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_LSB 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_RESET 0x1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_FIELD_MASK 0x00000002ul
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_GET(x) \
   (((x) & 0x00000002ul) >> 1)
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_SET(x) \
   (((x) << 1) & 0x00000002ul)
#define FKB_DIG_RCL_CSR_RRFSGCTL_DAC_BYPASS_SEL_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: fkb_dig_rcl_csr::rRfsgctl.en                              */
/* Source filename: rcl_csr.csr, line: 2061                                */
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_MSB 0u
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_LSB 0u
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_FIELD_MASK 0x00000001ul
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_GET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_SET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRFSGCTL_EN_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: fkb_dig_rcl_csr::rRfsgcfg                                */
/* Register template: fkb_dig_rcl_csr::rRfsgcfg                            */
/* Source filename: rcl_csr.csr, line: 2105                                */
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.freqDivPreload                  */
/* Source filename: rcl_csr.csr, line: 2305                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_MSB 31u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_LSB 28u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_WIDTH 4u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_FIELD_MASK 0xf0000000ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_GET(x) \
   (((x) & 0xf0000000ul) >> 28)
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_SET(x) \
   (((x) << 28) & 0xf0000000ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVPRELOAD_MODIFY(r, x) \
   ((((x) << 28) & 0xf0000000ul) | ((r) & 0x0ffffffful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.vcoDac                          */
/* Source filename: rcl_csr.csr, line: 2293                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_MSB 27u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_LSB 16u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_WIDTH 12u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_RESET 0x000u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_FIELD_MASK 0x0fff0000ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_GET(x) (((x) & 0x0fff0000ul) >> 16)
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_SET(x) (((x) << 16) & 0x0fff0000ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCODAC_MODIFY(r, x) \
   ((((x) << 16) & 0x0fff0000ul) | ((r) & 0xf000fffful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.diffDacEn                       */
/* Source filename: rcl_csr.csr, line: 2281                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_MSB 14u
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_LSB 14u
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_FIELD_MASK 0x00004000ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_GET(x) \
   (((x) & 0x00004000ul) >> 14)
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_SET(x) \
   (((x) << 14) & 0x00004000ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_DIFFDACEN_MODIFY(r, x) \
   ((((x) << 14) & 0x00004000ul) | ((r) & 0xffffbffful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.multResist5                     */
/* Source filename: rcl_csr.csr, line: 2265                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_MSB 13u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_LSB 13u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_FIELD_MASK 0x00002000ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_GET(x) \
   (((x) & 0x00002000ul) >> 13)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_SET(x) \
   (((x) << 13) & 0x00002000ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST5_MODIFY(r, x) \
   ((((x) << 13) & 0x00002000ul) | ((r) & 0xffffdffful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.multResist4                     */
/* Source filename: rcl_csr.csr, line: 2249                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_MSB 12u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_LSB 12u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_FIELD_MASK 0x00001000ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_GET(x) \
   (((x) & 0x00001000ul) >> 12)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_SET(x) \
   (((x) << 12) & 0x00001000ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST4_MODIFY(r, x) \
   ((((x) << 12) & 0x00001000ul) | ((r) & 0xffffeffful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.multResist3                     */
/* Source filename: rcl_csr.csr, line: 2233                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_MSB 11u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_LSB 11u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_FIELD_MASK 0x00000800ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_GET(x) \
   (((x) & 0x00000800ul) >> 11)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_SET(x) \
   (((x) << 11) & 0x00000800ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTRESIST3_MODIFY(r, x) \
   ((((x) << 11) & 0x00000800ul) | ((r) & 0xfffff7fful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.multGainX8                      */
/* Source filename: rcl_csr.csr, line: 2221                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_MSB 10u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_LSB 10u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_FIELD_MASK 0x00000400ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_GET(x) \
   (((x) & 0x00000400ul) >> 10)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_SET(x) \
   (((x) << 10) & 0x00000400ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX8_MODIFY(r, x) \
   ((((x) << 10) & 0x00000400ul) | ((r) & 0xfffffbfful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.multGainX4                      */
/* Source filename: rcl_csr.csr, line: 2209                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_MSB 9u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_LSB 9u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_FIELD_MASK 0x00000200ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_GET(x) \
   (((x) & 0x00000200ul) >> 9)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_SET(x) \
   (((x) << 9) & 0x00000200ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX4_MODIFY(r, x) \
   ((((x) << 9) & 0x00000200ul) | ((r) & 0xfffffdfful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.multGainX2                      */
/* Source filename: rcl_csr.csr, line: 2197                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_MSB 8u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_LSB 8u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_FIELD_MASK 0x00000100ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_GET(x) \
   (((x) & 0x00000100ul) >> 8)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_SET(x) \
   (((x) << 8) & 0x00000100ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_MULTGAINX2_MODIFY(r, x) \
   ((((x) << 8) & 0x00000100ul) | ((r) & 0xfffffefful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.atestSel                        */
/* Source filename: rcl_csr.csr, line: 2181                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_MSB 7u
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_LSB 4u
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_WIDTH 4u
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_FIELD_MASK 0x000000f0ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_GET(x) (((x) & 0x000000f0ul) >> 4)
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_SET(x) (((x) << 4) & 0x000000f0ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_ATESTSEL_MODIFY(r, x) \
   ((((x) << 4) & 0x000000f0ul) | ((r) & 0xffffff0ful))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.freqDivEn                       */
/* Source filename: rcl_csr.csr, line: 2165                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_MSB 3u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_LSB 3u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_FIELD_MASK 0x00000008ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_GET(x) (((x) & 0x00000008ul) >> 3)
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_SET(x) \
   (((x) << 3) & 0x00000008ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_FREQDIVEN_MODIFY(r, x) \
   ((((x) << 3) & 0x00000008ul) | ((r) & 0xfffffff7ul))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.hiSpdMuxSel                     */
/* Source filename: rcl_csr.csr, line: 2149                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_MSB 2u
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_LSB 2u
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_FIELD_MASK 0x00000004ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_GET(x) \
   (((x) & 0x00000004ul) >> 2)
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_SET(x) \
   (((x) << 2) & 0x00000004ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_HISPDMUXSEL_MODIFY(r, x) \
   ((((x) << 2) & 0x00000004ul) | ((r) & 0xfffffffbul))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.vcoEn                           */
/* Source filename: rcl_csr.csr, line: 2133                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_MSB 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_LSB 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_FIELD_MASK 0x00000002ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_GET(x) (((x) & 0x00000002ul) >> 1)
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_SET(x) (((x) << 1) & 0x00000002ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCOEN_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: fkb_dig_rcl_csr::rRfsgcfg.vcoRun                          */
/* Source filename: rcl_csr.csr, line: 2117                                */
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_MSB 0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_LSB 0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_WIDTH 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_WRITE_ACCESS 1u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_RESET 0x0u
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_FIELD_MASK 0x00000001ul
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_GET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_SET(x) ((x) & 0x00000001ul)
#define FKB_DIG_RCL_CSR_RRFSGCFG_VCORUN_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: fkb_dig_rcl_csr::rRend                                   */
/* Register template: fkb_dig_rcl_csr::rRend                               */
/* Source filename: rcl_csr.csr, line: 2319                                */
/* Field member: fkb_dig_rcl_csr::rRend.end                                */
/* Source filename: rcl_csr.csr, line: 2331                                */
#define FKB_DIG_RCL_CSR_RREND_END_MSB 31u
#define FKB_DIG_RCL_CSR_RREND_END_LSB 0u
#define FKB_DIG_RCL_CSR_RREND_END_WIDTH 32u
#define FKB_DIG_RCL_CSR_RREND_END_READ_ACCESS 1u
#define FKB_DIG_RCL_CSR_RREND_END_WRITE_ACCESS 0u
#define FKB_DIG_RCL_CSR_RREND_END_RESET 0x00000000ul
#define FKB_DIG_RCL_CSR_RREND_END_FIELD_MASK 0xfffffffful
#define FKB_DIG_RCL_CSR_RREND_END_GET(x) ((x) & 0xfffffffful)
#define FKB_DIG_RCL_CSR_RREND_END_SET(x) ((x) & 0xfffffffful)
#define FKB_DIG_RCL_CSR_RREND_END_MODIFY(r, x) ((x) & 0xfffffffful)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Memory: fkb_dig_rcl_csr::rclMemory                          */
/* Source filename: rcl_csr.csr, line: 1651                                */
typedef struct {
   uint8_t _pad0[0x2000];
} Fkb_dig_rcl_csr_rclMemory, *PTR_Fkb_dig_rcl_csr_rclMemory;

/* Typedef for Addressmap: fkb_dig_rcl_csr                                 */
/* Source filename: rcl_csr.csr, line: 2351                                */
typedef struct {
   Fkb_dig_rcl_csr_rclMemory rclMemory; /**< Offset 0x0 (R/W) */
   uint8_t _pad0[0xffe000];
   volatile uint32_t rRscratch; /**< Offset 0x1000000 (R/W) */
   volatile uint32_t rRctl; /**< Offset 0x1000004 (R/W) */
   volatile uint32_t rRcfg0; /**< Offset 0x1000008 (R/W) */
   volatile uint32_t rRcfg1; /**< Offset 0x100000c (R/W) */
   volatile uint32_t rRgs0; /**< Offset 0x1000010 (R) */
   volatile uint32_t rRgs1; /**< Offset 0x1000014 (R) */
   volatile uint32_t rRgs2; /**< Offset 0x1000018 (R) */
   volatile uint32_t rRfsgctl; /**< Offset 0x100001c (R/W) */
   volatile uint32_t rRfsgcfg; /**< Offset 0x1000020 (R/W) */
   uint8_t _pad1[0xffd8];
   uint32_t rRend; /**< Offset 0x100fffc (R) */
   uint8_t _pad2[0xff0000];
} Fkb_dig_rcl_csr, *PTR_Fkb_dig_rcl_csr;

#endif
