/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    Version: 2019.03 Build: release Linux 64-bit                         */
/*    C Header output                                                      */
/*                                                                         */
/* Command Line:                                                           */
/*    /home/cad/tools/semifore/csrcompiler/2019_03/bin/x64_re6/csrCompile  */
/*    -v -x CSRSpec -t h -t sv -t docx -a fkb_dig_csi_csr -o               */
/*    fkb_dig_csi_csr csi_csr.csr                                          */
/*                                                                         */
/* Input files:                                                            */
/*    csi_csr.csr                                                          */
/*                                                                         */
/* Generated on: Tue Sep  3 11:22:11 2019                                  */
/*           by: pasteinm                                                  */
/*                                                                         */

#ifndef _FKB_DIG_CSI_CSR_H_
#define _FKB_DIG_CSI_CSR_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: fkb_dig_csi_csr                           */
/* Source filename: csi_csr.csr, line: 4177                                */
/* Register: fkb_dig_csi_csr.rCscratch                                     */
#define FKB_DIG_CSI_CSR_RCSCRATCH_ADDRESS 0x0u
#define FKB_DIG_CSI_CSR_RCSCRATCH_BYTE_ADDRESS 0x0u
/* Register: fkb_dig_csi_csr.rCctl                                         */
#define FKB_DIG_CSI_CSR_RCCTL_ADDRESS 0x4u
#define FKB_DIG_CSI_CSR_RCCTL_BYTE_ADDRESS 0x4u
/* Register: fkb_dig_csi_csr.rCgs                                          */
#define FKB_DIG_CSI_CSR_RCGS_ADDRESS 0x8u
#define FKB_DIG_CSI_CSR_RCGS_BYTE_ADDRESS 0x8u
/* Register: fkb_dig_csi_csr.rCcmd                                         */
#define FKB_DIG_CSI_CSR_RCCMD_ADDRESS 0xcu
#define FKB_DIG_CSI_CSR_RCCMD_BYTE_ADDRESS 0xcu
/* Register: fkb_dig_csi_csr.rCcfg                                         */
#define FKB_DIG_CSI_CSR_RCCFG_ADDRESS 0x10u
#define FKB_DIG_CSI_CSR_RCCFG_BYTE_ADDRESS 0x10u
/* Register: fkb_dig_csi_csr.rCslvsel                                      */
#define FKB_DIG_CSI_CSR_RCSLVSEL_ADDRESS 0x14u
#define FKB_DIG_CSI_CSR_RCSLVSEL_BYTE_ADDRESS 0x14u
/* Register: fkb_dig_csi_csr.rCdr                                          */
#define FKB_DIG_CSI_CSR_RCDR_ADDRESS 0x18u
#define FKB_DIG_CSI_CSR_RCDR_BYTE_ADDRESS 0x18u
/* Register: fkb_dig_csi_csr.rCend                                         */
#define FKB_DIG_CSI_CSR_RCEND_ADDRESS 0xfffcu
#define FKB_DIG_CSI_CSR_RCEND_BYTE_ADDRESS 0xfffcu


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: fkb_dig_csi_csr                                        */
/* Addressmap template: fkb_dig_csi_csr                                    */
/* Source filename: csi_csr.csr, line: 3764                                */
#define FKB_DIG_CSI_CSR_SIZE 0x10000ul
#define FKB_DIG_CSI_CSR_BYTE_SIZE 0x10000ul
/* Register member: fkb_dig_csi_csr.rCscratch                              */
/* Register type referenced: fkb_dig_csi_csr::rCscratch                    */
/* Register template referenced: fkb_dig_csi_csr::rCscratch                */
#define FKB_DIG_CSI_CSR_RCSCRATCH_OFFSET 0x0u
#define FKB_DIG_CSI_CSR_RCSCRATCH_BYTE_OFFSET 0x0u
#define FKB_DIG_CSI_CSR_RCSCRATCH_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCSCRATCH_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCSCRATCH_RESET_VALUE 0x00000000ul
#define FKB_DIG_CSI_CSR_RCSCRATCH_RESET_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCSCRATCH_READ_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCSCRATCH_WRITE_MASK 0xfffffffful
/* Register member: fkb_dig_csi_csr.rCctl                                  */
/* Register type referenced: fkb_dig_csi_csr::rCctl                        */
/* Register template referenced: fkb_dig_csi_csr::rCctl                    */
#define FKB_DIG_CSI_CSR_RCCTL_OFFSET 0x4u
#define FKB_DIG_CSI_CSR_RCCTL_BYTE_OFFSET 0x4u
#define FKB_DIG_CSI_CSR_RCCTL_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCTL_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCTL_RESET_VALUE 0x00000000ul
#define FKB_DIG_CSI_CSR_RCCTL_RESET_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCCTL_READ_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCCTL_WRITE_MASK 0x80000001ul
/* Register member: fkb_dig_csi_csr.rCgs                                   */
/* Register type referenced: fkb_dig_csi_csr::rCgs                         */
/* Register template referenced: fkb_dig_csi_csr::rCgs                     */
#define FKB_DIG_CSI_CSR_RCGS_OFFSET 0x8u
#define FKB_DIG_CSI_CSR_RCGS_BYTE_OFFSET 0x8u
#define FKB_DIG_CSI_CSR_RCGS_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCGS_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCGS_RESET_VALUE 0x80000000ul
#define FKB_DIG_CSI_CSR_RCGS_RESET_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCGS_READ_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCGS_WRITE_MASK 0x800000f1ul
/* Register member: fkb_dig_csi_csr.rCcmd                                  */
/* Register type referenced: fkb_dig_csi_csr::rCcmd                        */
/* Register template referenced: fkb_dig_csi_csr::rCcmd                    */
#define FKB_DIG_CSI_CSR_RCCMD_OFFSET 0xcu
#define FKB_DIG_CSI_CSR_RCCMD_BYTE_OFFSET 0xcu
#define FKB_DIG_CSI_CSR_RCCMD_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCMD_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCMD_RESET_VALUE 0x00000000ul
#define FKB_DIG_CSI_CSR_RCCMD_RESET_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCCMD_READ_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCCMD_WRITE_MASK 0x7000fffful
/* Register member: fkb_dig_csi_csr.rCcfg                                  */
/* Register type referenced: fkb_dig_csi_csr::rCcfg                        */
/* Register template referenced: fkb_dig_csi_csr::rCcfg                    */
#define FKB_DIG_CSI_CSR_RCCFG_OFFSET 0x10u
#define FKB_DIG_CSI_CSR_RCCFG_BYTE_OFFSET 0x10u
#define FKB_DIG_CSI_CSR_RCCFG_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCFG_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCFG_RESET_VALUE 0x00000000ul
#define FKB_DIG_CSI_CSR_RCCFG_RESET_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCCFG_READ_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCCFG_WRITE_MASK 0x0000fffful
/* Register member: fkb_dig_csi_csr.rCslvsel                               */
/* Register type referenced: fkb_dig_csi_csr::rCslvsel                     */
/* Register template referenced: fkb_dig_csi_csr::rCslvsel                 */
#define FKB_DIG_CSI_CSR_RCSLVSEL_OFFSET 0x14u
#define FKB_DIG_CSI_CSR_RCSLVSEL_BYTE_OFFSET 0x14u
#define FKB_DIG_CSI_CSR_RCSLVSEL_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCSLVSEL_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCSLVSEL_RESET_VALUE 0x00000000ul
#define FKB_DIG_CSI_CSR_RCSLVSEL_RESET_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCSLVSEL_READ_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCSLVSEL_WRITE_MASK 0x000000fful
/* Register member: fkb_dig_csi_csr.rCdr                                   */
/* Register type referenced: fkb_dig_csi_csr::rCdr                         */
/* Register template referenced: fkb_dig_csi_csr::rCdr                     */
#define FKB_DIG_CSI_CSR_RCDR_OFFSET 0x18u
#define FKB_DIG_CSI_CSR_RCDR_BYTE_OFFSET 0x18u
#define FKB_DIG_CSI_CSR_RCDR_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCDR_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCDR_RESET_VALUE 0x00000000ul
#define FKB_DIG_CSI_CSR_RCDR_RESET_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCDR_READ_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCDR_WRITE_MASK 0xfffffffful
/* Register member: fkb_dig_csi_csr.rCend                                  */
/* Register type referenced: fkb_dig_csi_csr::rCend                        */
/* Register template referenced: fkb_dig_csi_csr::rCend                    */
#define FKB_DIG_CSI_CSR_RCEND_OFFSET 0xfffcu
#define FKB_DIG_CSI_CSR_RCEND_BYTE_OFFSET 0xfffcu
#define FKB_DIG_CSI_CSR_RCEND_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCEND_WRITE_ACCESS 0u
#define FKB_DIG_CSI_CSR_RCEND_RESET_VALUE 0x00000000ul
#define FKB_DIG_CSI_CSR_RCEND_RESET_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCEND_READ_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCEND_WRITE_MASK 0x00000000ul

/* Register type: fkb_dig_csi_csr::rCscratch                               */
/* Register template: fkb_dig_csi_csr::rCscratch                           */
/* Source filename: csi_csr.csr, line: 3785                                */
/* Field member: fkb_dig_csi_csr::rCscratch.Value                          */
/* Source filename: csi_csr.csr, line: 3797                                */
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_MSB 31u
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_LSB 0u
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_WIDTH 32u
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_RESET 0x00000000ul
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_FIELD_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_GET(x) ((x) & 0xfffffffful)
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_SET(x) ((x) & 0xfffffffful)
#define FKB_DIG_CSI_CSR_RCSCRATCH_VALUE_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: fkb_dig_csi_csr::rCctl                                   */
/* Register template: fkb_dig_csi_csr::rCctl                               */
/* Source filename: csi_csr.csr, line: 3813                                */
/* Field member: fkb_dig_csi_csr::rCctl.CIM                                */
/* Source filename: csi_csr.csr, line: 3847                                */
#define FKB_DIG_CSI_CSR_RCCTL_CIM_MSB 31u
#define FKB_DIG_CSI_CSR_RCCTL_CIM_LSB 31u
#define FKB_DIG_CSI_CSR_RCCTL_CIM_WIDTH 1u
#define FKB_DIG_CSI_CSR_RCCTL_CIM_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCTL_CIM_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCTL_CIM_RESET 0x0u
#define FKB_DIG_CSI_CSR_RCCTL_CIM_FIELD_MASK 0x80000000ul
#define FKB_DIG_CSI_CSR_RCCTL_CIM_GET(x) (((x) & 0x80000000ul) >> 31)
#define FKB_DIG_CSI_CSR_RCCTL_CIM_SET(x) (((x) << 31) & 0x80000000ul)
#define FKB_DIG_CSI_CSR_RCCTL_CIM_MODIFY(r, x) \
   ((((x) << 31) & 0x80000000ul) | ((r) & 0x7ffffffful))
/* Field member: fkb_dig_csi_csr::rCctl.CIF                                */
/* Source filename: csi_csr.csr, line: 3827                                */
#define FKB_DIG_CSI_CSR_RCCTL_CIF_MSB 0u
#define FKB_DIG_CSI_CSR_RCCTL_CIF_LSB 0u
#define FKB_DIG_CSI_CSR_RCCTL_CIF_WIDTH 1u
#define FKB_DIG_CSI_CSR_RCCTL_CIF_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCTL_CIF_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCTL_CIF_RESET 0x0u
#define FKB_DIG_CSI_CSR_RCCTL_CIF_FIELD_MASK 0x00000001ul
#define FKB_DIG_CSI_CSR_RCCTL_CIF_GET(x) ((x) & 0x00000001ul)
#define FKB_DIG_CSI_CSR_RCCTL_CIF_SET(x) ((x) & 0x00000001ul)
#define FKB_DIG_CSI_CSR_RCCTL_CIF_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: fkb_dig_csi_csr::rCgs                                    */
/* Register template: fkb_dig_csi_csr::rCgs                                */
/* Source filename: csi_csr.csr, line: 3867                                */
/* Field member: fkb_dig_csi_csr::rCgs.idle                                */
/* Source filename: csi_csr.csr, line: 3921                                */
#define FKB_DIG_CSI_CSR_RCGS_IDLE_MSB 31u
#define FKB_DIG_CSI_CSR_RCGS_IDLE_LSB 31u
#define FKB_DIG_CSI_CSR_RCGS_IDLE_WIDTH 1u
#define FKB_DIG_CSI_CSR_RCGS_IDLE_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCGS_IDLE_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCGS_IDLE_RESET 0x1u
#define FKB_DIG_CSI_CSR_RCGS_IDLE_FIELD_MASK 0x80000000ul
#define FKB_DIG_CSI_CSR_RCGS_IDLE_GET(x) (((x) & 0x80000000ul) >> 31)
#define FKB_DIG_CSI_CSR_RCGS_IDLE_SET(x) (((x) << 31) & 0x80000000ul)
#define FKB_DIG_CSI_CSR_RCGS_IDLE_MODIFY(r, x) \
   ((((x) << 31) & 0x80000000ul) | ((r) & 0x7ffffffful))
/* Field member: fkb_dig_csi_csr::rCgs.errorCount                          */
/* Source filename: csi_csr.csr, line: 3901                                */
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_MSB 7u
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_LSB 4u
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_WIDTH 4u
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_RESET 0x0u
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_FIELD_MASK 0x000000f0ul
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_GET(x) (((x) & 0x000000f0ul) >> 4)
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_SET(x) (((x) << 4) & 0x000000f0ul)
#define FKB_DIG_CSI_CSR_RCGS_ERRORCOUNT_MODIFY(r, x) \
   ((((x) << 4) & 0x000000f0ul) | ((r) & 0xffffff0ful))
/* Field member: fkb_dig_csi_csr::rCgs.error                               */
/* Source filename: csi_csr.csr, line: 3881                                */
#define FKB_DIG_CSI_CSR_RCGS_ERROR_MSB 0u
#define FKB_DIG_CSI_CSR_RCGS_ERROR_LSB 0u
#define FKB_DIG_CSI_CSR_RCGS_ERROR_WIDTH 1u
#define FKB_DIG_CSI_CSR_RCGS_ERROR_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCGS_ERROR_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCGS_ERROR_RESET 0x0u
#define FKB_DIG_CSI_CSR_RCGS_ERROR_FIELD_MASK 0x00000001ul
#define FKB_DIG_CSI_CSR_RCGS_ERROR_GET(x) ((x) & 0x00000001ul)
#define FKB_DIG_CSI_CSR_RCGS_ERROR_SET(x) ((x) & 0x00000001ul)
#define FKB_DIG_CSI_CSR_RCGS_ERROR_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: fkb_dig_csi_csr::rCcmd                                   */
/* Register template: fkb_dig_csi_csr::rCcmd                               */
/* Source filename: csi_csr.csr, line: 3949                                */
/* Field member: fkb_dig_csi_csr::rCcmd.rnw                                */
/* Source filename: csi_csr.csr, line: 4007                                */
#define FKB_DIG_CSI_CSR_RCCMD_RNW_MSB 30u
#define FKB_DIG_CSI_CSR_RCCMD_RNW_LSB 30u
#define FKB_DIG_CSI_CSR_RCCMD_RNW_WIDTH 1u
#define FKB_DIG_CSI_CSR_RCCMD_RNW_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCMD_RNW_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCMD_RNW_RESET 0x0u
#define FKB_DIG_CSI_CSR_RCCMD_RNW_FIELD_MASK 0x40000000ul
#define FKB_DIG_CSI_CSR_RCCMD_RNW_GET(x) (((x) & 0x40000000ul) >> 30)
#define FKB_DIG_CSI_CSR_RCCMD_RNW_SET(x) (((x) << 30) & 0x40000000ul)
#define FKB_DIG_CSI_CSR_RCCMD_RNW_MODIFY(r, x) \
   ((((x) << 30) & 0x40000000ul) | ((r) & 0xbffffffful))
/* Field member: fkb_dig_csi_csr::rCcmd.size                               */
/* Source filename: csi_csr.csr, line: 3983                                */
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_MSB 29u
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_LSB 28u
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_WIDTH 2u
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_RESET 0x0u
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_FIELD_MASK 0x30000000ul
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_GET(x) (((x) & 0x30000000ul) >> 28)
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_SET(x) (((x) << 28) & 0x30000000ul)
#define FKB_DIG_CSI_CSR_RCCMD_SIZE_MODIFY(r, x) \
   ((((x) << 28) & 0x30000000ul) | ((r) & 0xcffffffful))
/* Field member: fkb_dig_csi_csr::rCcmd.regAddr                            */
/* Source filename: csi_csr.csr, line: 3965                                */
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_MSB 15u
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_LSB 0u
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_WIDTH 16u
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_RESET 0x0000u
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_FIELD_MASK 0x0000fffful
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_GET(x) ((x) & 0x0000fffful)
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_SET(x) ((x) & 0x0000fffful)
#define FKB_DIG_CSI_CSR_RCCMD_REGADDR_MODIFY(r, x) \
   (((x) & 0x0000fffful) | ((r) & 0xffff0000ul))

/* Register type: fkb_dig_csi_csr::rCcfg                                   */
/* Register template: fkb_dig_csi_csr::rCcfg                               */
/* Source filename: csi_csr.csr, line: 4029                                */
/* Field member: fkb_dig_csi_csr::rCcfg.csclkDiv                           */
/* Source filename: csi_csr.csr, line: 4043                                */
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_MSB 15u
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_LSB 0u
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_WIDTH 16u
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_RESET 0x0000u
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_FIELD_MASK 0x0000fffful
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_GET(x) ((x) & 0x0000fffful)
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_SET(x) ((x) & 0x0000fffful)
#define FKB_DIG_CSI_CSR_RCCFG_CSCLKDIV_MODIFY(r, x) \
   (((x) & 0x0000fffful) | ((r) & 0xffff0000ul))

/* Register type: fkb_dig_csi_csr::rCslvsel                                */
/* Register template: fkb_dig_csi_csr::rCslvsel                            */
/* Source filename: csi_csr.csr, line: 4065                                */
/* Field member: fkb_dig_csi_csr::rCslvsel.bits                            */
/* Source filename: csi_csr.csr, line: 4079                                */
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_MSB 7u
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_LSB 0u
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_WIDTH 8u
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_RESET 0x00u
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_FIELD_MASK 0x000000fful
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_GET(x) ((x) & 0x000000fful)
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_SET(x) ((x) & 0x000000fful)
#define FKB_DIG_CSI_CSR_RCSLVSEL_BITS_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: fkb_dig_csi_csr::rCdr                                    */
/* Register template: fkb_dig_csi_csr::rCdr                                */
/* Source filename: csi_csr.csr, line: 4103                                */
/* Field member: fkb_dig_csi_csr::rCdr.data                                */
/* Source filename: csi_csr.csr, line: 4119                                */
#define FKB_DIG_CSI_CSR_RCDR_DATA_MSB 31u
#define FKB_DIG_CSI_CSR_RCDR_DATA_LSB 0u
#define FKB_DIG_CSI_CSR_RCDR_DATA_WIDTH 32u
#define FKB_DIG_CSI_CSR_RCDR_DATA_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCDR_DATA_WRITE_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCDR_DATA_RESET 0x00000000ul
#define FKB_DIG_CSI_CSR_RCDR_DATA_FIELD_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCDR_DATA_GET(x) ((x) & 0xfffffffful)
#define FKB_DIG_CSI_CSR_RCDR_DATA_SET(x) ((x) & 0xfffffffful)
#define FKB_DIG_CSI_CSR_RCDR_DATA_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: fkb_dig_csi_csr::rCend                                   */
/* Register template: fkb_dig_csi_csr::rCend                               */
/* Source filename: csi_csr.csr, line: 4145                                */
/* Field member: fkb_dig_csi_csr::rCend.end                                */
/* Source filename: csi_csr.csr, line: 4157                                */
#define FKB_DIG_CSI_CSR_RCEND_END_MSB 31u
#define FKB_DIG_CSI_CSR_RCEND_END_LSB 0u
#define FKB_DIG_CSI_CSR_RCEND_END_WIDTH 32u
#define FKB_DIG_CSI_CSR_RCEND_END_READ_ACCESS 1u
#define FKB_DIG_CSI_CSR_RCEND_END_WRITE_ACCESS 0u
#define FKB_DIG_CSI_CSR_RCEND_END_RESET 0x00000000ul
#define FKB_DIG_CSI_CSR_RCEND_END_FIELD_MASK 0xfffffffful
#define FKB_DIG_CSI_CSR_RCEND_END_GET(x) ((x) & 0xfffffffful)
#define FKB_DIG_CSI_CSR_RCEND_END_SET(x) ((x) & 0xfffffffful)
#define FKB_DIG_CSI_CSR_RCEND_END_MODIFY(r, x) ((x) & 0xfffffffful)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: fkb_dig_csi_csr                                 */
/* Source filename: csi_csr.csr, line: 4177                                */
typedef struct {
   volatile uint32_t rCscratch; /**< Offset 0x0 (R/W) */
   volatile uint32_t rCctl; /**< Offset 0x4 (R/W) */
   volatile uint32_t rCgs; /**< Offset 0x8 (R/W) */
   volatile uint32_t rCcmd; /**< Offset 0xc (R/W) */
   volatile uint32_t rCcfg; /**< Offset 0x10 (R/W) */
   volatile uint32_t rCslvsel; /**< Offset 0x14 (R/W) */
   volatile uint32_t rCdr; /**< Offset 0x18 (R/W) */
   uint8_t _pad0[0xffe0];
   uint32_t rCend; /**< Offset 0xfffc (R) */
} Fkb_dig_csi_csr, *PTR_Fkb_dig_csi_csr;

#endif
